# Generated by Django 5.1.6 on 2025-02-22 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Food",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("description", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=255)),
                ("calorie_conversion_factor_protein", models.FloatField(null=True)),
                ("calorie_conversion_factor_fat", models.FloatField(null=True)),
                ("calorie_conversion_factor_carbs", models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Nutrient",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("description", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=255)),
                ("unit", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="FoodNutrient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.FloatField()),
                (
                    "food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="usda_sync.food"
                    ),
                ),
                (
                    "nutrient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usda_sync.nutrient",
                    ),
                ),
            ],
            options={
                "unique_together": {("food", "nutrient")},
            },
        ),
    ]
