# Generated by Django 5.1.6 on 2025-02-22 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usda_sync", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="FoodNutrient",
            new_name="FoodSpecs",
        ),
    ]
