# Generated by Django 5.1.6 on 2025-02-22 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usda_sync", "0003_alter_foodspecs_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodspecs",
            name="amount",
            field=models.FloatField(default=0),
        ),
    ]
