# Generated by Django 5.1.6 on 2025-02-23 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usda_sync", "0004_alter_foodspecs_amount"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="FoodSpecs",
            new_name="FoodSpec",
        ),
    ]
