# Generated by Django 5.1.6 on 2025-02-23 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usda_sync", "0005_rename_foodspecs_foodspec"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nutrient",
            name="category",
        ),
    ]
