# Generated by Django 5.1.6 on 2025-02-23 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usda_sync", "0006_remove_nutrient_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="LastUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField(blank=True, default="", max_length=255)),
            ],
        ),
    ]
