# Generated by Django 5.1.6 on 2025-03-04 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usda_sync', '0007_lastupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodspec',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
