# Generated by Django 5.1.6 on 2025-02-13 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition_matcher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='fatContent',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='proteinContent',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='sugarContent',
            field=models.IntegerField(null=True),
        ),
    ]
