# Generated by Django 5.1.6 on 2025-02-22 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition_matcher", "0002_food_fatcontent_food_proteincontent_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Food",
        ),
    ]
